
package GUI;

import LogicaDifusa.LogicaDifusa;
import Modelo.Recomendacion;
import gestorBD.Controlador;


public class InterfazLogica extends javax.swing.JFrame {
    
    public InterfazLogica() {
        initComponents();
        
        sliderRitmo.setValue(5);
        sliderLetra.setValue(5);
        sliderMomento.setValue(5);
        repaint();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sliderRitmo = new javax.swing.JSlider();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sliderLetra = new javax.swing.JSlider();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sliderMomento = new javax.swing.JSlider();
        botonCalificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificación de la recomendación"));
        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 0, 3));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setText("¿Qué tal le pareció el ritmo de la canción?");
        jPanel3.add(jLabel2);

        sliderRitmo.setMajorTickSpacing(1);
        sliderRitmo.setMaximum(10);
        sliderRitmo.setMinorTickSpacing(1);
        sliderRitmo.setPaintLabels(true);
        sliderRitmo.setPaintTicks(true);
        jPanel3.add(sliderRitmo);

        jPanel2.add(jPanel3);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setText("¿Qué tal le pareció la letra de la canción?");
        jPanel10.add(jLabel3);

        sliderLetra.setMajorTickSpacing(1);
        sliderLetra.setMaximum(10);
        sliderLetra.setPaintLabels(true);
        sliderLetra.setPaintTicks(true);
        jPanel10.add(sliderLetra);

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel4.setText("¿Qué tan adecuada fue la recomendación de esta canción para el momento?");
        jPanel11.add(jLabel4);

        sliderMomento.setMajorTickSpacing(1);
        sliderMomento.setMaximum(10);
        sliderMomento.setPaintLabels(true);
        sliderMomento.setPaintTicks(true);
        jPanel11.add(sliderMomento);

        jPanel2.add(jPanel11);

        botonCalificar.setText("Enviar calificación");
        botonCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(botonCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Evaluación de la recomendación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalificarActionPerformed
        int ritmo = sliderRitmo.getValue();
        int letra = sliderLetra.getValue();
        int momento = sliderMomento.getValue();

        Recomendacion.calificacion = LogicaDifusa.calcularCalificacionRecomendacion(ritmo, letra, momento);
        
        Controlador.guardarCalificacion();
        dispose();
        //TODO si Nico es un vago se debe guardar el XML al cerrar esta ventana
        
    }//GEN-LAST:event_botonCalificarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalificar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider sliderLetra;
    private javax.swing.JSlider sliderMomento;
    private javax.swing.JSlider sliderRitmo;
    // End of variables declaration//GEN-END:variables
}
